// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb9_5qXEJhxKqHJda5nyBbvy-LcTRlsrY',
    appId: '1:45868455938:web:379472ecfd8f7e85ca2f1b',
    messagingSenderId: '45868455938',
    projectId: 'gurk-spy',
    authDomain: 'gurk-spy.firebaseapp.com',
    storageBucket: 'gurk-spy.firebasestorage.app',
    measurementId: 'G-E75QH3W33V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1YdtC8UeZkFci51ilzzb6SYuvIBaJyKs',
    appId: '1:45868455938:android:70d566e4a871430aca2f1b',
    messagingSenderId: '45868455938',
    projectId: 'gurk-spy',
    storageBucket: 'gurk-spy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDC30vOWHNe2l3_E9LfNTXJ94UGH3vTSo',
    appId: '1:45868455938:ios:8ae5a09734fa17baca2f1b',
    messagingSenderId: '45868455938',
    projectId: 'gurk-spy',
    storageBucket: 'gurk-spy.firebasestorage.app',
    iosBundleId: 'com.example.gurkSpy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDC30vOWHNe2l3_E9LfNTXJ94UGH3vTSo',
    appId: '1:45868455938:ios:8ae5a09734fa17baca2f1b',
    messagingSenderId: '45868455938',
    projectId: 'gurk-spy',
    storageBucket: 'gurk-spy.firebasestorage.app',
    iosBundleId: 'com.example.gurkSpy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb9_5qXEJhxKqHJda5nyBbvy-LcTRlsrY',
    appId: '1:45868455938:web:162f17189e93afb7ca2f1b',
    messagingSenderId: '45868455938',
    projectId: 'gurk-spy',
    authDomain: 'gurk-spy.firebaseapp.com',
    storageBucket: 'gurk-spy.firebasestorage.app',
    measurementId: 'G-HFQF52ETER',
  );
}